--
-- Indexes for table `permission`
--
ALTER TABLE `PERMISSION`
  ADD PRIMARY KEY (`PERMISSION_ID`),
  MODIFY `PERMISSION_ID` int(11) NOT NULL AUTO_INCREMENT;
--
-- Indexes for table `role`
--
ALTER TABLE `ROLE`
  ADD PRIMARY KEY (`ROLE_ID`),
  MODIFY `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT;
--
-- Indexes for table `permission_role`
--
ALTER TABLE `PERMISSION_ROLE`
  ADD PRIMARY KEY (`PERMISSION_ROLE_ID`),
  ADD KEY `ROLE_ID` (`ROLE_ID`),
  ADD KEY `PERMISSION_ID` (`PERMISSION_ID`),
  ADD CONSTRAINT `FK_PR_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`),
  ADD CONSTRAINT `FK_PR_PERMISSION` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSION` (`PERMISSION_ID`),
  MODIFY `PERMISSION_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT;
--
-- Indexes for table `person`
--
ALTER TABLE `PERSON`
  ADD PRIMARY KEY (`PERSON_ID`),
  MODIFY `PERSON_ID` INT(11) NOT NULL AUTO_INCREMENT;
--
-- Indexes for table `user`
--
ALTER TABLE `USER`
  ADD PRIMARY KEY (`USER_ID`),
  ADD KEY `PERMISSION_ID` (`PERMISSION_ID`),
  ADD KEY `PERSON_ID` (`PERSON_ID`),
  ADD CONSTRAINT `FK_U_PERMISSION` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSION` (`PERMISSION_ID`),
  ADD CONSTRAINT `FK_U_PERSON` FOREIGN KEY (`PERSON_ID`) REFERENCES `PERSON` (`PERSON_ID`),
  MODIFY `USER_ID` INT(11) NOT NULL AUTO_INCREMENT;
--
-- Indexes for table `hotel`
--
ALTER TABLE `HOTEL`
  ADD PRIMARY KEY (`HOTEL_ID`),
  MODIFY `HOTEL_ID` INT(11) NOT NULL AUTO_INCREMENT;
 --
 -- Indexes for table `ROOM`
 -- 
 ALTER TABLE `ROOM`
  ADD PRIMARY KEY (`ROOM_ID`),
  ADD KEY `HOTEL_ID` (`HOTEL_ID`),
  ADD CONSTRAINT `FK_R_HOTEL` FOREIGN KEY (`HOTEL_ID`) REFERENCES `HOTEL` (`HOTEL_ID`),
  MODIFY `ROOM_ID` INT(11) NOT NULL AUTO_INCREMENT;
COMMIT;